IF NOT EXISTS (SELECT 1
			   FROM INFORMATION_SCHEMA.TABLES 
               WHERE TABLE_SCHEMA = N'dbo' AND  TABLE_NAME = N'Languages')
BEGIN
	CREATE TABLE [dbo].[Languages]
	(
		Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
		Code VARCHAR(2) NOT NULL,
		Name NVARCHAR(50) NOT NULL,
	)
END
